In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('./data/data.csv')


In [14]:
df.head()
df['target_name'].unique()

array(['1P28D', '_1P28D', '3P28D', '_3P28D', '_5P28D', '5P28D', '_10P28D',
       '10P28D', '_15P28D', '15P28D'], dtype=object)

In [15]:
df['ticker'].unique()

array(['ZTS', 'ZTO', 'ZS', 'ZION', 'ZEN', 'ZBRA', 'ZBH', 'ZAYO', 'Z',
       'YY', 'YUMC', 'YUM', 'YPF', 'YNDX', 'YELP', 'XRX', 'XRAY', 'XPO',
       'XPER', 'XOM', 'XLNX', 'XENT', 'XEC', 'X', 'WYNN', 'WY', 'WWE',
       'WU', 'WST', 'WSM', 'WRK', 'WPM', 'WMT', 'WMB', 'WM', 'WLL', 'WIX',
       'WING', 'WHR', 'WFC', 'WELL', 'WDC', 'WDAY', 'WCG', 'WBC', 'WBA',
       'WB', 'WAT', 'WAB', 'W', 'VZ', 'VTR', 'VSM', 'VRTX', 'VRSN',
       'VRSK', 'VOD', 'VNOM', 'VNDA', 'VMW', 'VMC', 'VLO', 'VIAB', 'VFC',
       'VEEV', 'VC', 'VAR', 'VALE', 'VAC', 'V', 'UTX', 'USCR', 'USB',
       'URI', 'URBN', 'UPS', 'UNP', 'UNH', 'UN', 'ULTA', 'UL', 'UAL',
       'UAA', 'UA', 'TXRH', 'TXN', 'TWTR', 'TWO', 'TWLO', 'TTWO', 'TTM',
       'TTD', 'TSN', 'TSM', 'TSLA', 'TSEM', 'TSCO', 'TRV', 'TROX', 'TROW',
       'TRIP', 'TRGP', 'TREX', 'TPX', 'TPR', 'TOT', 'TOL', 'TNDM', 'TMUS',
       'TMO', 'TLRY', 'TKR', 'TJX', 'TIF', 'TGT', 'TEX', 'TEVA', 'TER',
       'TEN', 'TECK', 'TECD', 'TEAM', 'TDG', 'TD', 'TAP', 'TA

In [5]:
ALL_DATES = []
for date in (df['eval_date'].unique()):
    ALL_DATES.append(date)

In [6]:
CURRENT_MODELS = []
MODEL_DICT          = {} 
temp = df['modelid'].unique()

for i,num in enumerate (temp):
    MODEL_DICT [i+1]=num
    CURRENT_MODELS.append(num)

In [7]:
MODEL_DICT.values()

dict_values([3376, 4445, 2901, 3755, 4658])

In [8]:
df[(df['modelid'] == 4658) & (df['eval_date'] == "10/17/2018" )].empty

True

In [13]:
import numpy
import pandas as pd

print(numpy.version.version)
print(pd.__version__)

1.16.2
0.24.2


In [9]:
CURRENT_EVAL_DATE = "2018-10-01"
model = 3376 
print (float(df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )]["percent_change"].astype(float)))
print (float(df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )]["USD_change"].astype(float)))
print (float(df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )]["probability"].astype(float)))

11.3101
3.695
0.6019553242148092


In [10]:
import numpy as np
frame = np.empty(shape=[0, 4])

for model in MODEL_DICT.values():
    print (model, CURRENT_EVAL_DATE)
    if df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )].empty:
            print ("Data frame empty for model:", model, "eval_data", CURRENT_EVAL_DATE)
    else:
        frame = np.append(frame, [[
            model,
            float(df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )]["percent_change"].astype(float)),
            float(df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )]["USD_change"].astype(float)),
            float(df[(df['modelid'] == int(model)) & (df['eval_date'] == CURRENT_EVAL_DATE )]["probability"].astype(float))

        ]], axis=0)
print (frame)

3376 2018-10-01
4445 2018-10-01
2901 2018-10-01
3755 2018-10-01
4658 2018-10-01
[[3.37600000e+03 1.13101000e+01 3.69500000e+00 6.01955324e-01]
 [4.44500000e+03 1.13101000e+01 3.69500000e+00 6.56238632e-01]
 [2.90100000e+03 1.13101000e+01 3.69500000e+00 8.18825548e-01]
 [3.75500000e+03 1.13101000e+01 3.69500000e+00 6.43870069e-01]
 [4.65800000e+03 1.13101000e+01 3.69500000e+00 6.82998401e-01]]


In [157]:
df[(df['modelid'] == 3755) & (df['eval_date'] == CURRENT_DATE )]

modelid ticker   eval_date  probability   index  targetid  target_val  \
296171     3755   FAST  10/17/2018      0.64387  666770       NaN           1   

       target_name  percent_change  USD_change   rating  
296171       1P28D         26.0741       9.285  0.64387

In [83]:
current_step=0

(df[(df['modelid'] == 3755) & (df['eval_date'] == CURRENT_DATE )]["probability"])


286360    0.64387
Name: probability, dtype: float64

In [71]:
import math

TARGET_NAME         = "1P28D"
CURRENT_REWARD      = 0
MAX_REWARD          = 2147483647

current_probability = float(df[(df['modelid'] == 3755) & (df['eval_date'] == CURRENT_DATE )]["probability"])
current_target_val  = int  (df[(df['modelid'] == 3755) & (df['eval_date'] == CURRENT_DATE )]["target_val"])

if "_" in TARGET_NAME:
    if current_target_val == 0:
        CURRENT_REWARD += math.pow(MAX_REWARD, current_probability)
    else:
        CURRENT_REWARD -= math.pow(MAX_REWARD, current_probability)
else:
    if current_target_val == 1:
        CURRENT_REWARD += math.pow(MAX_REWARD, current_probability)
    else:
        CURRENT_REWARD -= math.pow(MAX_REWARD, current_probability)
    

print(CURRENT_REWARD)

1019882.937893418


In [15]:
MODEL_DICT[2]

4658

In [88]:
CURRENT_MODELS

[3755, 4658, 4445, 3376, 2901]

In [95]:
for model in MODEL_DICT.values():
    print (model)

3755
4658
4445
3376
2901


In [45]:
CURRENT_MODELS
selected_model = 5

In [46]:
if (MODEL_DICT[selected_model] in CURRENT_MODELS):  
    CURRENT_MODELS.remove(MODEL_DICT[selected_model])

In [47]:
CURRENT_MODELS

[4658, 3376]